### ISSUE TITLE
Setup CI-Pipeline

### ISSUE THREAD

**Issue by Daniel-Seifert** [Daniel-Seifert/Guide-007#2]
# Description

Setup full CI-Pipeline with project automation.

# Tasks

- [ ] CI with Github Actions
- [ ] Connect to Sonarcloud
- [ ] Run Tests
- [ ] Push image to Docker Hub
