### ISSUE TITLE
Implement ZPA-Schedule

### ISSUE THREAD

**Issue by Daniel-Seifert** [Daniel-Seifert/Guide-007#4]
# Description

In order to display the ZPA-Schedule in our app, we need to query upcoming events from the REST-Interface of ZPA.

Following URL shows how to receive events for one week:
https://zpa.cs.hm.edu/student/ws_get_week_plan/?date=2019-12-01

# Tasks

- [x] Implement own store-module to receive and cache calendar entries from ZPA
- [ ] Add timeline view for current day
- [ ] Add view to display all events per week
